### ISSUE TITLE
I’d like to help testing

### ISSUE THREAD

**Issue by smeevil** [y24o2/Alexa-Skill-for-Netatmo-Healthy-Home-Coach#2]
Hi,

I’d like to help with the testing :)
Is the skill only working in German or English as well ? 

Let me know if you’d like me to help out, and how to install the skill :)

Gerard

**Comment by heytommy** [comment]
Me too.

**Comment by y24o2** [comment]
The Skill works in englisch,  too. 

Please let me know, how many home coaches do you own?

I need your Amazon email address to invite you to beta test.

The Skill should be available for you when your email address is on beta test.

**Comment by heytommy** [comment]
hi,

I have two home coaches. My amazon email is weiprecht@gmail.com

-- 
Thomas Weiprecht

**Comment by smeevil** [comment]
Hi,

I have one home coach for now. My email is info@govannon.nl

**Comment by y24o2** [comment]
invite sent

**Comment by heytommy** [comment]
Sorry I didnt get any. Can you please resend it? Ty

-- 
Thomas Weiprecht
